title: PONG

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true

plugins:
  - jekyll-watch

exclude:
  - "*.gem"
  - "*.gemspec"
  - README.md
  - LICENSE
  - Rakefile
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - ".github"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title/
      toc: true
  - scope:
      path: ""
      type: lans
    values:
      layout: lan
      permalink: /lans/:title/

collections:
  tabs:
    output: true
    permalink: /:name/
    sort_by: order
  lans:
    output: true
